# Generated by Django 6.0.3 on 2026-05-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='female',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='male',
        ),
    ]
