# Generated by Django 6.0.3 on 2026-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_remove_salon_female_remove_salon_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
