# Generated by Django 6.0.3 on 2026-05-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_salon_female_salon_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='haircut_price',
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='service_images/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shopkeeper.salon')),
            ],
        ),
    ]
