# Generated by Django 6.0.3 on 2026-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_remove_salon_haircut_price_salonservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='female',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='male',
        ),
        migrations.AddField(
            model_name='salonservice',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
