# Generated by Django 6.0.3 on 2026-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_remove_salon_female_remove_salon_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
