# Generated by Django 6.0.3 on 2026-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_salonimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='salon_image',
            field=models.ImageField(default=2, upload_to='salon_image/'),
            preserve_default=False,
        ),
    ]
