# Generated by Django 6.0.3 on 2026-06-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_salon_salon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('about_service', models.TextField()),
                ('service_image', models.ImageField(upload_to='service/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.salon')),
            ],
        ),
    ]
