# Generated by Django 6.0.3 on 2026-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='about_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
