# Generated by Django 6.0.3 on 2026-06-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_alter_service_about_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonservice',
            name='female',
        ),
        migrations.RemoveField(
            model_name='salonservice',
            name='male',
        ),
        migrations.AddField(
            model_name='salonservice',
            name='target_gender',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('unisex', 'Unisex (Both)')], default='unisex', max_length=10),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
