# Generated by Django 6.0.3 on 2026-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_remove_salonservice_female_remove_salonservice_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
