# Generated by Django 6.0.3 on 2026-06-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0011_salon_latitude_salon_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='address',
        ),
    ]
