# Generated by Django 6.0.3 on 2026-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0012_remove_salon_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
