# Generated by Django 6.0.3 on 2026-06-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0014_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='shopkeeper.salonservice'),
        ),
    ]
