# Generated by Django 6.0.3 on 2026-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0015_queueentry_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='silder')),
            ],
        ),
    ]
