# Generated by Django 6.0.3 on 2026-06-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0016_siderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
