# Generated by Django 6.0.3 on 2026-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0017_alter_siderimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
