# Generated by Django 6.0.3 on 2026-08-18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shopkeeper', '0018_salonservice_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='salon_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='feedbacks', to='shopkeeper.salon')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='salonfeedback',
            constraint=models.UniqueConstraint(fields=('salon', 'customer'), name='unique_customer_salon_feedback'),
        ),
        migrations.AddConstraint(
            model_name='salonfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_between_1_and_5'),
        ),
    ]
